import { NextRequest, NextResponse } from 'next/server';
import { revalidatePath } from 'next/cache';
import { getUser, saveUser, readUsers } from '@/lib/storage';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

// Copy/duplicate a user profile
export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { username } = body;

        if (!username || typeof username !== 'string') {
            return NextResponse.json({ error: 'Username is required' }, { status: 400 });
        }

        // Get the original user
        const originalUser = await getUser(username);
        if (!originalUser) {
            return NextResponse.json({ error: 'User not found' }, { status: 404 });
        }

        // Get all existing users to find a unique username
        const allUsers = await readUsers();
        const existingUsernames = allUsers.map(u => u.username.toLowerCase());

        // Find a unique username by adding a numeric suffix
        let newUsername = username;
        let suffix = 1;

        while (existingUsernames.includes(newUsername.toLowerCase())) {
            newUsername = `${username}${suffix}`;
            suffix++;
        }

        // Create the duplicate user with the new username
        const userData = {
            profilePicture: originalUser.profilePicture,
            bio: originalUser.bio,
            links: originalUser.links.map(link => ({
                id: '', // Will be generated by the database
                title: link.title,
                url: link.url,
                order: link.order,
            })),
            listedBy: originalUser.listedBy || null,
            theme: originalUser.theme || 'standard',
        };

        console.log('Copying user:', username, 'to', newUsername);

        const copiedUser = await saveUser(newUsername, userData);

        if (!copiedUser) {
            return NextResponse.json(
                { error: 'Failed to copy user. Check server logs for details.' },
                { status: 500 }
            );
        }

        console.log('User copied successfully:', newUsername);

        // Revalidate admin pages
        revalidatePath('/admin');
        revalidatePath(`/${newUsername}`);

        return NextResponse.json({
            user: copiedUser,
            message: `Profile copied successfully as "${newUsername}"`
        });
    } catch (error: any) {
        console.error('Error copying user:', error);
        return NextResponse.json(
            { error: error.message || 'Failed to copy user' },
            { status: 500 }
        );
    }
}
